UIG-975 first pull request
milieuinfo/webcomponent-vl-ui-tabs pull request #1
Opened 2021-01-19 14:53 UTC by SBylemans

2021-01-27 13:32 UTC, coemans requested changes

2021-01-27 13:32 UTC, coemans commented on src/vl-tabs.js
> +        <ul id="tabList" class="vl-tabs vl-tabs--alt" data-vl-tabs-list role="tablist">
We kunnen best al een data-vl-alt attribuut introduceren zodat beide varianten beschikbaar zijn.

2021-01-27 13:32 UTC, coemans commented on src/vl-tabs.js
> +          <span>Navigatie</span>
Best niet hard coderen maar de mogelijkheid voorzien om de tekst aan te passen via attribuut, setter en/of slot element.

2021-01-27 13:32 UTC, coemans commented on src/vl-tabs.js
> +}
Best een afzonderlijk bestand voorzien voor vl-tab-pane implementatie en een vl-tabs-all.js bestand introduceren.

2021-01-27 13:32 UTC, coemans commented on src/vl-tabs.js
> +      const id = tp.getAttribute('data-vl-id');
Best getters voorzien op vl-tab-pane.

2021-01-27 13:32 UTC, coemans commented on src/vl-tabs.js
> +        </li>
Best deze HTML niet lekken in vl-tabs, maar bijvoorbeeld een template getter voorzien op vl-tab niveau. De title en id getters van hierboven zijn dan overbodig.

2021-01-27 13:32 UTC, coemans commented on src/vl-tabs.js
> +  }
Ik zou hier een afzonderlijk component van maken die de gebruiker als onderdeel van vl-tabs content kan toevoegen. De koppeling met de panes kan dan aan de hand van attributen gebeuren.

2021-01-27 13:32 UTC, coemans commented on test/e2e/tabs.test.js
> +  });
Best nog e2e testen voorzien.

2021-01-27 13:32 UTC, coemans commented on test/unit/vl-tabs.test.html
> +    });
Best nog unit testen voorzien.

2021-01-27 13:32 UTC, coemans commented on lib/tabs.js
> +(function (global, factory) {
Wijzigingen zullen afzonderlijk in de issues bekeken en opgevolgd worden.

2021-01-27 13:32 UTC, coemans commented on package.json
> +		"@govflanders/vl-ui-util": "^3.12.3",
De @govflanders core en util zijn dev dependencies.

2021-01-27 13:32 UTC, coemans commented on package.json
> +		"simple-git": "^2.31.0",
Mag verwijderd worden, komt voorlopig nog onterecht automatisch mee via vl-blueprint.

2021-02-02 09:45 UTC, SBylemans commented on src/vl-tabs.js
> +        </li>
Is het de bedoeling om een vl-tabs, vl-tab en vl-tab-pane te voorzien?

2021-02-02 09:51 UTC, coemans commented on src/vl-tabs.js
> +        </li>
Ik zou inderdaad een vl-tab introduceren om de code meer logisch te bundelen en beter te kunnen testen. De vl-tab moet niet lekken naar de afnemer, kan puur intern gebruik zijn. De huidige API lijkt me OK.

2021-02-02 10:28 UTC, coemans commented on package.json
> +		"simple-git": "^2.31.0",
Werd opgelost in #initial branch.

2021-02-02 10:31 UTC, coemans commented on package.json
> +		"@govflanders/vl-ui-util": "^3.12.3",
Werd opgelost in #initial branch.

2021-02-02 14:45 UTC, coemans commented on test/e2e/tabs.test.js
> +  });
Werd opgelost in #initial branch.

2021-02-10 10:05 UTC, closed without merging