Navigatie naar pagina's met subpath
milieuinfo/webcomponent-vl-ui-tabs pull request #19
Opened 2021-02-19 15:59 UTC by SBylemans

Fix voor issue met bovenstaande titel

2021-02-22 12:39 UTC, Rubenth approved these changes

2021-02-22 14:01 UTC, coemans requested changes
De unit testen

2021-02-22 14:01 UTC, coemans commented on src/vl-tabs.js
> +    setTimeout(() => this.__dress(true), 0);
Deze wijziging lijkt niet nodig te zijn, dus heb ik verwijderd.

2021-02-22 14:01 UTC, coemans commented on demo/vl-tabs.html
>    <link rel="stylesheet" type="text/css" href="/node_modules/vl-ui-demo/dist/style.css">
Ik heb hiervoor een nieuwe demo pagina gemaakt om de bestaande niet te beïnvloeden en zeker te zijn van de werking indien er geen base tag gebruikt wordt.

2021-02-22 14:01 UTC, coemans commented on src/vl-tabs.js
>      `);
Deze wijzigingen breken de unit testen, best de testen aanpassen.

2021-02-22 16:05 UTC, SBylemans commented on src/vl-tabs.js
> +    setTimeout(() => this.__dress(true), 0);
Die is wel nodig... Toch zeker de setTimeout. In Safari 14.0.3 zorgt dit ervoor dat een nieuw toegevoegde tab niet clickbaar is (event listener wordt niet gezet)

2021-02-22 16:12 UTC, SBylemans commented on src/vl-tabs.js
>      `);
Aangepast

2021-02-22 16:40 UTC, coemans approved these changes

2021-02-22 16:55 UTC, coemans commented on src/vl-tabs.js
> +    setTimeout(() => this.__dress(true), 0);
In dit geval kan er perfect een unit test geschreven worden met vermelding/beschrijving van de Safari bug/fix. Ik begrijp nog niet waarom de `setTimeout` een probleem zou oplossen, aangezien in de dress functie de listener geregistreerd worden zonder asynchroniteit.

Wanneer de drivers het toelaten, zullen er op webcomponent niveau Safari testen toegevoegd worden waardoor dit probleem wel naar boven was gekomen.

2021-02-22 17:23 UTC, coemans commented on src/vl-tabs.js
> +    setTimeout(() => this.__dress(true), 0);
Ik heb het probleem ondertussen verder onderzocht in Safari (13.x.x) en de huidige oplossing zal niet altijd werken. Ik heb een nieuw voorstel gedaan. Kan je applicatief eens testen of het werkt? Als het werkt, zal ik de testen die nu (terecht) falen nog fixen en kan er gemengde worden.

2021-02-23 07:36 UTC, coemans commented
PR werd aangemaakt om centraal uitbreiding aan lib door te voeren.

2021-02-23 09:16 UTC, SBylemans commented on src/vl-tabs.js
> +    setTimeout(() => this.__dress(true), 0);
@coemans lijkt in orde applicatief.

2021-02-23 09:42 UTC, merged